services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hh-app
    user: "1000:1000"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - hh

  nginx:
    image: nginx:1.27-alpine
    container_name: hh-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - hh

  postgres:
    image: postgres:16-alpine
    container_name: hh-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - hh_postgres_data:/var/lib/postgresql/data
    networks:
      - hh

networks:
  hh:
    driver: bridge

volumes:
  hh_postgres_data:
